### ISSUE TITLE
Mobile Layout

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#133]
Need to implement mobile layout found in the dropbox

**Comment by AllieDeford** [comment]
Is this considered done with the switch the the horizontal nav (#193)?

**Comment by radioprotector** [comment]
I don't think so, but it's a lot better.

For example, we need to ensure that the nav will collapse properly in Mobile views.

I also want to do a thorough audit of all of our current screens to make sure they still look good (although I'm not too worried about most of them).

**Comment by radioprotector** [comment]
For more reference, here's what I'm talking about regarding the nav:
![navbar](https://cloud.githubusercontent.com/assets/8010294/6994897/dfd3a6e2-daf7-11e4-9926-89e8bc19e97d.png)

The floated logo in the Jumbotron is also odd in smaller views:
![jumbotron](https://cloud.githubusercontent.com/assets/8010294/6994904/04549a08-daf8-11e4-9992-010423d9150a.png)
