### ISSUE TITLE
Solution for Small Non-mobile screens

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#134]
As pointed out by @radioprotector, the site currently looks bad on small, non-mobile screens such as a netbook screen. In addition to generally making the font size and other similar things (which I am already planning on doing), we need to decide how to handle this. For example, should we show the mobile site on screens smaller than 12 inches? Should we just make everything smaller so that it looks a bit smaller on large screens but good on the smaller screens? Should there be a slightly modified desktop view for smaller screens (7-13 inches maybe)?

**Comment by radioprotector** [comment]
I think that the new nav changes as well as any changes for #133 will address this.
