### ISSUE TITLE
Update deployment guide

### ISSUE THREAD

**Issue by radioprotector** [radremedy/radremedy#166]

**Comment by radioprotector** [comment]
@AllieDeford - I've added a new [wiki page](https://github.com/radremedy/radremedy/wiki/Deploying-the-App) but I decided not to link it in the sidebar (it's still available in the "Pages" dropdown).

If you think it's good, we can close this out.

**Comment by AllieDeford** [comment]
I looked at this today, and I'm happy with it. After #189 is accepted, I'll try to deploy the new version so that I can make sure everything works as I expect. But I'm considering this issue closed.
