### ISSUE TITLE
Arrows for new provider cards aren't stable in layout

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#177]
Sometimes they look okay, sometimes they don't. Depends on screen size and zoom-ed in factor. 

![screenshot](https://cloud.githubusercontent.com/assets/6627658/6407199/731d31f4-bdf0-11e4-8197-0aa7d25028e7.png)

For example, like this

**Comment by radioprotector** [comment]
I'm wondering - do we actually need to include a scroller? How many items are we planning on including in this list? If it's only 5 or so, and we typically show 4, is it worth the hassle to get the scroller to work when only one or two items will be outside of the scrolled view?

We might be able to get away with just using floated [panels](http://getbootstrap.com/components/#panels) (I'm assuming they can be floated) or a list group with some custom styling. I think that might work better in mobile views.

**Comment by radioprotector** [comment]
I did a mockup of my idea using panels. Here's what I came up with:

![recently-added-rework](https://cloud.githubusercontent.com/assets/8010294/6519529/42da6a50-c383-11e4-94cf-2a455490e01a.PNG)
