### ISSUE TITLE
Write "How to use RAD" guide

### ISSUE THREAD

**Issue by radioprotector** [radremedy/radremedy#181]
This page is currently marked as under construction and so we should fill it in or remove references to if if we're not going to have it available for the initial version.

**Comment by radioprotector** [comment]
At present all links to this page are currently commented out but can be easily re-added once we have a guide.

**Comment by lovecultivated** [comment]
I am going to try to get us to work on this from the car tomorrow, because nothing says fun like writing work on a 12 hour car ride...
