### ISSUE TITLE
Include category description in text searching

### ISSUE THREAD

**Issue by radioprotector** [radremedy/radremedy#184]
This serves as a good alternative to having a hierarchical category system.

**Comment by radioprotector** [comment]
One alternative: do we just want a separate "keywords" field to use instead of the description? That might work a little better, particularly if we start allowing for browsing of categories (which would most likely entail displaying the description for each category).

**Comment by AllieDeford** [comment]
I'm a little unclear on what you mean. How is the keywords field different from the category field? Is this the description of the category?

**Comment by radioprotector** [comment]
I think this was a meeting that you missed, but we discussed how we wanted to handle categories and text searching (particularly since we didn't have a hierarchy).

We settled on the idea of having fewer categories, but including synonyms and specializations in the category description. To ensure that those synonyms/specializations are included in the text searching, we need to modify the way the `category_text` field on each resource is [generated](https://github.com/radremedy/radremedy/blob/master/remedy/rad/models.py#L195) - it currently only incorporates the name of each associated category.

I'm wondering if we want to keep keywords separate from the description of the category. I'm currently favoring that approach right now.

**Comment by AllieDeford** [comment]
We talked about it a little bit tonight at the meeting, and I think I finally understand the problem. I think that sounds like a good plan and since you've been handling all the database and searching stuff, I think whatever you are favoring is fine
