### ISSUE TITLE
Add way for logged-in users to suggest new resources

### ISSUE THREAD

**Issue by radioprotector** [radremedy/radremedy#185]
Continuing [the discussion from #182](https://github.com/radremedy/radremedy/pull/182#issuecomment-77666188), we could have a suggestion form for logged in users.

This would be linked to from the search page when no results are available, and if we update the "Recently Added" portion on the front page to filter based on location, we could add it there as well.

**Comment by AllieDeford** [comment]
At the meeting tonight, there was general frustration vented about how data is the one thing holding us back, and we're just not having traction getting it entered. So we floated the idea of what a launch would look like it we just went ahead, and what would need to be accomplished. Besides general cleanup and making sure the search works the way we want it to, the biggest problem that came up is that there currently isn't a form for submitting resources, so this should become a higher priority

**Comment by AllieDeford** [comment]
This will migrate from a Google Form to a built in form. @radioprotector and @lovecultivated (because I feel like the two of you are most likely to have opinions on this), when a new resource is added, should it be directly added to the database or should there a be a sort of 'holding pen' where resources need to be approved by an admin before they are added? 

Also, are they required to leave a review of the provider in order to suggest them?

**Comment by radioprotector** [comment]
It definitely needs a holding pen.

I think we'd need to add a `submitted_user_id` FK column and a `proposed` Boolean column (default to false in both the app and on the database server, non-null) to the Resource model.

I think a review would not be required. Potentially we wouldn't even want to include that yet.

**Comment by rileydjohnson** [comment]
I feel a holding pen and a review required is important. Holding pen for
QA. A review requirement helps to vet a provider that we don't have listed
and make sure that the folks suggesting a provider have actually seen them.

Thanks,
Riley

**Comment by lovecultivated** [comment]
Undecided currently on the holding pen vs database. Leaning towards a
holding pen so somebody does add a bunch of providers with bs reviews.

Yes on the review. Required to do a rating and open box comment in order
for it to be added

**Comment by radioprotector** [comment]
@internetcreep: Here's what I have so far.


## Functional Overview

### Submitting Resources

We'll have a form with the following fields in this order:

- Provider Information
	* Provider Name (required)
	* Organization
	* Description
	* Address
	* Phone Number
	* Fax
	* Email
	* Website
	* Office Hours
	* Categories (using the standard multiselect)
	* Populations Served (using the standard multiselect)
	* Hospital Affiliation
	* NPI
	* Other Notes
- Review
	* Rating (required)
	* Intake Rating
	* Staff Rating
	* Review Text (required)

Behind the scenes, we'll also track:
- Submitted IP
- Submitted User
- Source (will go in as "`user - <username>`")

We'll make the following options always available even if the current user isn't logged in, but update the login process to redirect them to their requested page upon a successful login:

- Submit a Provider
- Add a Review
- Submit a Correction

All submitted resources will default to active but not approved. Approving a resource will toggle the approved flag, but rejecting a resource will change the status to inactive.

From an Admin perspective, we'll have a "Pending Submissions" section under the "Resource" option. From there, each individual resource will have "Save", "Approve", "Reject", and "Cancel" options. Resources can be deleted from this view but not created.

I can look into trying to get some duplicate detection in but I fear that's going to be pretty difficult to manage.

### Searching Resources

We will update all standard resource retrievals to filter on having a status of approved. Attempting to go to a single unapproved resource will result in "Not Found".

### Future Steps

I think we need to start separating out the "Settings" page on the user profile. Instead of linking to the "Settings" from the main layout page when someone's logged in, we should instead link to a new "Profile" option with the following sections:

- Profile details (Essentially the "My Profile" part that's currently there), with a link to edit them
- My Reviews (Showing only visible top-level reviews on active/approved providers)
- My Submitted Resources
- Change My Password link

This probably ties in to some of the work outlined in #250 a bit.

**Comment by internetcreep** [comment]
Yessss to pretty much everything!

We should probably go ahead and include all the fields currently in the RAD Record Format, which I think is just the new flags that are missing from the current list.

Clarification, will people have to login still to do reviews/suggestions/corrections?

I am also very excited about the future profile suggestions.

**Comment by internetcreep** [comment]
I was just thinking that I wouldn't want someone who doesn't have an account  to fill out the provider form to then suddenly be told they gotta sign up.

**Comment by radioprotector** [comment]
Okay. The new flags probably shouldn't be too difficult.

Yes, they'll still have to log in. The login requirement applies when you go to any of these forms initially, so you have to log in before you can start filling them out. I think that resolves your concern on that last point.

Basically the process is:
- Click link (like "Submit a Provider")
- Get kicked over to the login screen
- Log in
- Get redirected to the provider submission page
- Fill out and submit as normal

**Comment by internetcreep** [comment]
Thanks for clarifying. That sounds good. Could we also add some text
somewhere along the way that says something like "We're excited to hear
from you! In order to establish community accountability, you'll need to
login/sign up to proceed. Thanks for contributing!"

**Comment by radioprotector** [comment]
It appears that we can fairly easily adjust the [default message that gets flashed](https://flask-login.readthedocs.org/en/latest/#customizing-the-login-process) when someone gets sent to the login screen.

**Comment by radioprotector** [comment]
For my own reference and for others later on:


## Technical Changes

### Database Changes

We will update the `submitted_user_id` field on the `Resource` model to use `ondelete='SET NULL'`.

### Signin Changes

We'll update Flask-Login to the latest stable version (0.3.0). This will require changing a few places that check is_authenticated to invoke it as a property instead of a method. In the `user_auth` module we'll update the `login_manager.login_message` to something a little more user-friendly.

In addition, we'll override the `is_active` property to check the `active` field.

We'll change the `auth.sign_in` endpoint to recognize the `next` query string parameter as outlined in the [Flask-Login documentation](https://flask-login.readthedocs.org/en/latest/). We'll have to propagate the `next` query string parameter within the `login.html` form.

We'll remove the following `logged_in` checks in `find-provider.html`:
- Submit a Correction (two places)
- Add a Review

### Admin Changes

We'll add an "Approved" filter to the Admin resource views.

For WTForms overrides, we'll create new `PlainTextWidget` and `PlainTextField` classes that will render out plain text as appropriate. In the latter case, we'll override the `validate` method to always return True and override the `process` method to always use the field's default.

#### New View

We will add a new `SubmittedResourceView` to the `resourceview.py` file. This view will *not* expose the "Approved", "Visible", or "Date Verified" columns. Resources cannot be created in this model.

This will override the `get_count_query` and `get_query` methods to filter on having a non-null `submitted_ip` as well a `visible` value of True and a `is_approved` value of False. We'll use a `prepare_submitted_query` method to consolidate this like how we do it in the other views.

This will override the `edit_form` method to perform the following operations:

- Retrieve the submitted user (`submitted_user_text`), submitted IP (`submitted_ip_text`), and submitted date (`submitted_date_text`) and add the results as `PlainTextField` instances
- Retrieve potential dupes and add the result (a comma-separated list of names/IDs, or "None Detected" if none are found, as `potential_dupes`) as a `PlainTextField`
- Retrieve review fields and add the results (`review_rating`, `review_intake_rating`, `review_staff_rating`, `review_text`) as `PlainTextField` instances

This will override the `on_model_change` method to perform the following operations (we'll still call the parent method to ensure `last_updated` gets updated:

- If `_approve_resource` is in `request.form`, it will update `is_approved` to True and set the `date_verified` to the current date.
- If `_reject_resource` is in `request.form`, it will update `is_active` to False.

This will override the `form_rules` property to group things in a semantically-appropriate way.

#### New Template

We will add a new `submitted_resource_edit.html` template for editing submitted resources.

This will have the following overrides:
- The `body` block will be overridden so that its `render_form` library call passes in the necessary extra action buttons (using the names handled by the `on_model_change` override above) instead of the standard "Save and ..." buttons. We'll still render out the `navlinks` sub-block as normal.
- The `tail` block will be updated to render out the necessary Google maps initialization, like how we handle resource editing/creation.

## User-Facing Submissions

### Form/Template Changes

We will add the following internal mixins for composing different forms:
- `SubmitProviderBaseForm` (will contain all provider fields outlined in the functional spec)
- `ReviewBaseForm` (will contain all review fields outlined in the functional spec)

We'll change the `ReviewForm` to use the new `ReviewBaseForm` mixin. We'll add a new `UserSubmitProviderForm` which will incorporate both mixins above.

A new template, `add-provider.html`, will be used for submitting a new provider.

The template data that can be shared between the `add-review.html` and `add-provider.html` templates will be extracted out to a new partial template, `review-block.html`. 

#### Endpoint Changes

A new `submit_provider` method will be added to `remedyblueprint` to handle submission of new providers. This will create a new resource based on the provided data, and add special handling for `is_approved=False`, `source`, `submitted_user_id`, `submitted_ip`, and `submitted_date`.

Once the resource is saved, it will call `session.flush()`, add the associated review, and then commit all the changes.

We'll update the following areas to link to this new endpoint:
- `about-the-beta.html`
- `base.html` (twice)
- `find-provider.html` (twice)

### Resource Retrieval Changes

The `resourceservice.search` method will be updated to support filtering on `is_approved` as a flag.

The following `remedyblueprint` methods to will be updated to filter on `is_approved=True`:
- `latest_added`
- `latest_reviews` (also needs to filter on `visible=True`)
- `resource_with_id` (also needs to filter on `visible=True`)
- `resource_search`

The `ReviewForm.validate_provider` method will be updated to use `remedyblueprint.resource_with_id`.
