### ISSUE TITLE
City/State locations 

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#187]
There have been a few discussions where it has been mentioned that it would be nice to know the city and state of a resource, generally for display purposes. The two times this comes to mind are on the 'recently added to RAD' cards and in search results (see @lovecultivated 's comment in #179). 

We could either add this as a separate field to the RAD Record format, or we could do something like [this](http://stackoverflow.com/questions/13428284/get-city-state-from-latitude-longitude-via-jquery-ajax-with-google-maps-geocode), which uses Google maps to reverse geocode and just get the city and state. 

Thoughts?

**Comment by radioprotector** [comment]
Okay, so I think I have a decent idea of the changes this will take.


This new field will be filled with address information in the format "City, State/Province". In the case of there being no city, it will attempt to use the county as a fallback. At this point, I'm not sure if we want to include a country as well, although that'd be easy enough to add.

From a Google Maps geocoding perspective, the information will be read from the first item in [`address_components`](https://developers.google.com/maps/documentation/geocoding/#JSON) that uses the specified type:

- City (`locality`)
- State (`administrative_area_level_1`)
- County (`administrative_area_level_2`)

The `short_name` will be preferred to `long_name` in each address component.

A new `location` `UnicodeText` column will be added to the `Resource` model.

The geopy library will be upgraded to use 1.10.0 (the docs currently don't even list 1.1).

The geocoder will be updated to:
- Use the `exactly_one` argument when geocoding.
- Check the returned location's [`raw`](https://geopy.readthedocs.org/en/1.10.0/#geopy.location.Location.raw) value and attempt to generate a `location` value based on the provided `address_components` as outlined previously.

`db_fun`'s `get_or_create_resource` method will be updated to clear out `Resource.location` when the other geocoding information is invalidated as the result of an address change.

In the Admin `resourceview`, the `action_remove_address` method will be updated to clear out `Resource.location` along with all of the other geocoding information.

The `gmaps_script` macro will be updated to include an additional optional `location` parameter. When set, it will attempt to set the value of this field to a constructed short address based on the geocoded `place` returned by the Google Maps API, which has the previously-mentioned `address_components` value. The places that use general localities, such as a user's default location and the location searching fields, will not use this parameter.

In the corresponding Admin creation/editing templates, `resource_create.html` and `resource_edit.html`, the `location` control group will be hidden and wired up using the aforementioned `gmaps_script` macro change.

The recently-added list in `index.html` and the list of search results in `find-provider.html` will be updated to include this location.
