### ISSUE TITLE
Add option to reset password from email

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#188]
As opposed to just by username

**Comment by radioprotector** [comment]
If I recall, the reason we did it by username and not email initially is for privacy reasons.

I suppose we could pretend that every email address results in a successful reset email submitted even when it doesn't correspond with a user.

**Comment by zitterbewegung** [comment]
What if a user forgets their username? They won't forget their email.

**Comment by radioprotector** [comment]
Do we want to switch entirely over to email or allow either option, then?

**Comment by AllieDeford** [comment]
I say allowing either option is industry standard, so I'd vote for that

**Comment by rileydjohnson** [comment]
Sounds good to me.
R.
