### ISSUE TITLE
Figure out details for provider page

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#204]
The provider page has a place for information, including sliding scale, accepting new patients, WPATH/ICATH standards, etc. But, we can't display this information until we store it, and we want to make sure we're storing the right information. So we need someone to help us make a list of things that should go in this box.

**Comment by lovecultivated** [comment]
I have started a list of "ideal things we shall have when we start calling people" and will take a look at it and refine it. 

Note that some things that we haven't thought of may come up as we start talking to people, but we will get there.

**Comment by AllieDeford** [comment]
It's fine if it's not perfect, but we want a good starting point before we go mucking around with the database

**Comment by lovecultivated** [comment]
This is what we currently have:

Top Box:
•	Sliding Scale
•	Accepts Insurance (Hot link to Insurance Accepted area? Is there a better way to do this?)
•	Accepting New Patient
•	Languages Spoken
•	Follows ICATH Standards/Follows WPATH Standards/Follows ICATH or WPATH Standards/Nothing present so it doesn’t show


Side Box:
•	Organization Name (if different from the provider)
•	All the contact info (looks good over here)


Description and Underneath Description:
*most of these will be auto closed, if they are present, so people can click an arrow and look at them if they want – signified by DD*
•	Description
•	Services Provided (DD)
o      specific services in addition to the service up top tags (this could eventually solve the overwhelming service tag list, but would be something that would need to be resolved when we are doing provider-specific outreach)
•	Insurance Accepted (DD)
•	Other Info About this Provider (DD)
o	orgs often do their own research or questionnaires that we won’t do, but we want to be able to provide a place for it… we talked briefly about this re: ICAH’s Youth Research… we want to be able to let them attach this info in their format and it open in another window for perusal


Other:
•	If possible, to have organization specific notes for folks from places like the Trans Life Line to track comments and stuff that is specific to their org. THIS IS NOT IMPORTANT RIGHT NOW AT ALL.
•	Some folks in the needs assessment asked for a picture of the provider. Unsure how to do this and unsure how to work it in

**Comment by lovecultivated** [comment]
Ok, I am a liar and didn't catch that the Org Name was under the Provider Name. We should leave that there and not in the side box.

**Comment by radioprotector** [comment]
Is there anything actionable on this for the 0.1 release, or does the addition of the Notes field give us what we need for right now?

**Comment by lovecultivated** [comment]
Notes is good for now!

**Comment by radioprotector** [comment]
I think I broke this out into enough separate issues so that everything's covered. I'll close this now.
