### ISSUE TITLE
Add columns to reviews

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#214]
As per the email today, I suggest removing the rating column from the reviews model and adding 3 similar columns for intake_rating, provider_rating, and staff_rating. 

I was also thinking about the possibility of not removing the rating column and storing an internal aggregate which we could maybe use in the future as a way to sort for highly rated reviews. @radioprotector, what do you think about this?

**Comment by radioprotector** [comment]
I like the idea of an internal aggregate simply because I don't want the additional hassle of trying to remove or otherwise ignore the existing `rating` field, which is a pain in SQLite (you have to basically drop the table and re-add it without the columns).

**Comment by AllieDeford** [comment]
That sounds good to me :)

**Comment by radioprotector** [comment]
After further inspection, `rating` is already an integer column, and so to appease SQLite, I think what I will do is add `intake_rating` and `staff_rating` as integer columns, use `rating` in place of `provider_rating`, and have a new floating-point `composite_rating` column.
