### ISSUE TITLE
Add new data to live database

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#215]
There is a bunch of cleaned data in the dropbox that we need to add to the production database before the site goes live

**Comment by radioprotector** [comment]
Categories are in and old resources are gone. The resources can go in once #212 is closed.

**Comment by radioprotector** [comment]
Excel is doing a bad job at exporting CSVs in the way we want them (quotes and commas in the actual provider information really throws it off). I'm going to have to write a VBA macro to export this properly :/

**Comment by radioprotector** [comment]
Initial set of resources and categories are in. I didn't need to write a VBA macro after all after addressing some initial encoding issues with #212. Thankfully.
