### ISSUE TITLE
Investigate issues with location-based searching

### ISSUE THREAD

**Issue by radioprotector** [radremedy/radremedy#229]
- Searching by zip code does not appear to work consistently in the autocomplete (seems to be OK in header but not on the actual search page itself)
- We should default the distance to something like 25 miles even when a location's not specified so that it's not confusing when someone *does* select a location

**Comment by internetcreep** [comment]
I noticed another weird quirk. When using the "advanced search page," if my search yeilds 0 results, instead of getting the "no results" page, I instead get the last search I ran (if i haven't ran a search or have emptied my cache, I *think* it might default to my default location, but I'm not positive). However, when using the "header search," it works fine.

**Comment by internetcreep** [comment]
I'm not sure if this is a google maps issue or something on our end, but on the search results map, you can't really click on the different map markers. It just keeps highlighting the same one, no matter where I click.

**Comment by internetcreep** [comment]
I was also thinking that having a default distance (25 miles seems good to me) would help with location based searches. Go team!

Two other (hopefully) small (and low priority) thoughts: 
Could we increase the number of miles people can search by to... say 200 miles? 
Is there a way users can choose how many results show up on one page? I think it's defaulting to 15 right now.

**Comment by radioprotector** [comment]
I think you suggested that default distance originally when I did the writeup.
The marker thing is something on our end that I fixed (*shakes fist angrily at JavaScript*).
I'm also adding a 200 miles option.

I don't want to make the page too slow with the results (particularly plotting them in JavaScript). I'll bump it up to 20.

**Comment by rileydjohnson** [comment]
I think we are at the point where subsequent suggestions should roll into
the .2 release. They're helpful but we really should roll what we have
before taking on additional suggestions, probably. Hope that's okay with
tech wizards. We know we will have to tweak and debug anyway.
Thanks,
Riley
