### ISSUE TITLE
Investigate forcing HTTPS for anything that requires authentication

### ISSUE THREAD

**Issue by radioprotector** [radremedy/radremedy#243]
This is for general security purposes so that passwords and sensitive cookie information is not transmitted in the clear.

**Comment by radioprotector** [comment]
This would affect the following endpoints:
- `/signup/`
- `/login/`
- `/logout/`
- `/confirm-account/`
- `/request-reset/`
- `/reset-password/`
- `/change-password/`
- `/review/`
- `/delete-review/`
- `/settings/`
- `/admin/`

How do y'all feel about forcing HTTPS for all of those areas?

Since omitting the trailing slash automatically redirects to the version with the trailing slash, we can be pretty specific about those routings when we're configuring Apache.

**Comment by AllieDeford** [comment]
I think enforcing HTTPS in these situations makes sense, especially the stuff related to passwords

**Comment by radioprotector** [comment]
I think I got this resolved, but it involved a lot of pain and trial-and-error. Essentially, I managed to get the httpd.conf to recognized the necessary rewrite rules, but it was heavily dependent on the order in which I declared them relative to the other items in that file.

:-1:
