### ISSUE TITLE
Revisit Documentation

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#244]
Much of our documentation hosted here on GitHub is out of date and should be updated to reflect current progress

**Comment by radioprotector** [comment]
@AllieDeford: I updated a lot of the wiki pages tonight and removed/consolidated pages where appropriate. Do you think we need to make any further changes?

I guess the one sticking point now is what kind of instructions we want to give people in terms of getting started with a new provider database. I think it might be time to update the `rad-dev-db` database and standardize on using that for new developers.

That also means we can delete all the bootstrapping/scraping code (for which I opened #261) and simplify that section of the documentation.

**Comment by radioprotector** [comment]
I've updated the sample database with some acceptable data and so at this point I don't feel it's necessary to walk people through the scraping/bootstrapping process if they want some data to work with. I removed references to that process from the wiki.

**Comment by AllieDeford** [comment]
I looked through the wiki and these are the notes I made: 

Home- The problem 
Technically true, but sort of out of date with our mission? 

Contributing- Overall Status 
mention making organization accounts 

Getting started- 
Move A Note for Windows Developers to the bottom 

Preferred Pronoun page- 
why does this exist?

**Comment by radioprotector** [comment]
Are you referring to the second half of the problem? Yeah, I'll adjust that.

I thought organizational accounts would be covered by the latter half of "Making it easier for providers to submit and maintain information".

The note for Windows Developers is a prerequisite for installing the requirements - i've personally experienced pip failing without it. I can fold it in as a subsection to the setup process though.

Wil made the preferred pronoun page a while ago. I'm OK with getting rid of it.

**Comment by radioprotector** [comment]
I updated those pages you mentioned. I added some clarification to the Contributing portion to make it more clear what we intend for submission. I also cleaned up the introduction section to the RAD Record format page.

**Comment by radioprotector** [comment]
Allie's good with this now.
