### ISSUE TITLE
Make Google address/location fields automatically select the first option

### ISSUE THREAD

**Issue by radioprotector** [radremedy/radremedy#256]
Based on some searching, apparently we're not the only people with this issue -  Google's `place_changed` events don't fire in an intuitive way.

It's not obvious to people that they need to select something from the autocomplete to make it take effect, so we should default to the first location even when the user doesn't explicitly select something.

**Comment by AllieDeford** [comment]
I can't remember-- what was the problem with auto selecting the first place? Because I think that would be a good stop-gap measure for fixing this problem while we look for other solutions

**Comment by radioprotector** [comment]
I couldn't get it to work consistently. 

I started looking at solutions like was [suggested on SO](https://stackoverflow.com/questions/10772282/google-maps-places-api-v3-autocomplete-select-first-option-on-enter-and-have).

However, the search employed there only seems to support specific addresses, not geographic places, and I couldn't find anything in the [Places API](https://developers.google.com/maps/documentation/javascript/places#place_searches) that would support the kind of searching we're looking to do.

We might be able to use the [AutocompleteService](https://developers.google.com/maps/documentation/javascript/reference#AutocompleteService), but I think we'd have to do some extra stuff because I think those services only return the associated place ID, which we'd have to make an additional query to actually get the latitude/longitude we need based on that place ID.
