### ISSUE TITLE
Add flags (WPATH, ICATH, ADA/Wheelchair Accessible, Sliding Scale) and hospital affiliations to providers

### ISSUE THREAD

**Issue by radioprotector** [radremedy/radremedy#283]
As identified in the 8/19/2015 meeting.

**Comment by radioprotector** [comment]
## Functional Overview

We will be adding the following fields to the RAD Record format (with the corresponding CSV column names):

- Hospital Affiliation (`hospital_affiliation`, a multi-line free-text field)
- Informed Consent (ICATH) Provider (`is_icath`, a flag)
- WPATH Provider (`is_wpath`, a flag)
- ADA/Wheelchair Accessible (`wheelchair_accessible`, a flag)
- Sliding Scale (`sliding_scale`, a flag)

The flag fields will recognize the following column values (case-insensitive):

- `True`
- `False`
- `Yes`
- `No`
- `Y`
- `N`
- `1`
- `0`

A blank value will be interpreted as unknown.

The provider search page will be expanded with "Informed Consent/ICATH", "WPATH", "ADA/Wheelchair Accessible", and "Sliding Scale" checkboxes.

Having a flag set for a resource will add keywords to the hidden field used in text searching (which currently includes category/population names):

- *Informed Consent/ICATH*: `informed consent ICATH`
- *WPATH*: `WPATH`
- *ADA/Wheelchair Accessible*: `ADA accessible wheelchair accessible`
- *Sliding Scale*: `sliding scale`

The hospital affiliation will not be included in text searching.

On the provider page, these new flags will be listed out between the categories and description fields. We will only render out flags that have an explicit value set (I want to avoid displaying a ton of "Unknown" values).

The affiliated hospital will be listed on each provider after the list of populations served.

From an administrative perspective, the new flags will be available as filters on the resource views. We will not have any mass-actions currently enabled for these flags.

We will also not be including hospital affiliation in text searching.

## Tech Changes

### RAD Record Changes

We will add the fields outlined above to the `RadRecord` structure.

We will have a general-purpose `convert_boolean` that will coerce values into `True`, `False`, or `None` as appropriate according to the guidelines above.

We will also add a `normalize_record` method on the RadRecord structure that will perform value coercion on the new flag fields. In addition, it will also call the existing `convert_category_name` and `convert_population_names` methods to have a single normalization function that can be used.

In that vein, we will update `get_radrecord` in the `data_importer` module to call this new `normalize_record` method.

### Database/Model Changes

We will add the following fields to the `Resource` model:

- `is_icath`: Boolean, nullable
- `is_wpath`: Boolean, nullable
- `is_accessible`: Boolean, nullable
- `has_sliding_scale`: Boolean, nullable
- `hospital_affiliation`: Unicode text, nullable

The `normalize_resource` method will be updated to add keywords to the category_text field based on the presence of the field as outlined above.

We will update the `get_or_create_resource` method in the `db_fun` module to copy over the equivalent RadRecord fields over to the resource model it sets up.

### Admin Changes

We will add filters to the Resource view as outlined above. We will also be adding custom labels for these fields so that they display a little more nicely.

### Provider/Searching Pages

We will update `resourceservice.search` to support filtering on provided boolean values for the relevant flag fields (using the following keys in the provided `search_params` dict):

- `icath`
- `wpath`
- `sliding_scale`
- `wheelchair_accessible`

The `searchutils` module will be expanded with an additional `add_bool` value that will coerce a form value (which should be `0` or `1`, although we will currently only expose a value of `1`) to a `True` or `False` value as appropriate.

The `remedyblueprint.resource_search` endpoint will be updated to accept form values that mirror what is supported by the above `resourceservice.search` method.

The `provider.html` and `find-provider.html` templates will be updated to support displaying/searching on the fields provided.

**Comment by internetcreep** [comment]
From what I understood, here are my thoughts:

For keywords, I might add to "handicap accessible" to ADA/Wheelchair Accessible, and "sliding fee" to Sliding Scale.

So for the flags, if it there is no value, the field will not show up on the page. But if the value is False, will it show up? I'm assuming when the flags are checked on the search page, it will only pull up the True results?

**Comment by radioprotector** [comment]
Okay, I'll add those keywords.

Yes to both of those questions.

**Comment by internetcreep** [comment]
Great. Thanks for the clarification. That is helpful.
