### ISSUE TITLE
Add feedback to location fields to indicate when one is selected

### ISSUE THREAD

**Issue by radioprotector** [radremedy/radremedy#292]
I'm thinking that we can use the [Bootstrap validation classes](http://getbootstrap.com/css/#forms-control-validation) to highlight when a valid location is selected.

When there's text in the location box, and we have actual latitude/longitude values, it will appear with a green checkbox in it.

Attempting to type or change the text in the location box will clear out the current latitude/longitude values behind the scenes, and will appear with a yellow warning until a location is selected in the autocomplete (or the geolocation stuff is used).

When there's no text in the location field, there will be no icon.

**Comment by internetcreep** [comment]
Sounds good to me!
