### ISSUE TITLE
Add a blurb about crowdfunding to home page

### ISSUE THREAD

**Issue by internetcreep** [radremedy/radremedy#300]
We'll get you the copy and images soon, but I wanted to put this on your radar, cause we're gonna start pushing soon.

**Comment by internetcreep** [comment]
![fb crowdfunding banner](https://cloud.githubusercontent.com/assets/7097315/10316412/ccc2166a-6c24-11e5-8718-18b573095f80.jpg)

in dropbox/RAD Business/Grants & Fundraising/Crowdfunding/fb crowdfunding banner.jpg

Unless you think we need more text, just the image with a link to the rockethub: https://www.rockethub.com/projects/61520-rad-remedy-be-a-part-of-the-remedy

**Comment by internetcreep** [comment]
But don't make it live yet. Hopefully tomorrow? Will let you know

**Comment by internetcreep** [comment]
Because I think a mobile-specific resolution would look bad on a desktop. Here is an idea. 
![fb crowdfunding banner-pt1](https://cloud.githubusercontent.com/assets/7097315/10327794/5d93cc96-6c71-11e5-9aff-df74e7c1b3af.jpg)
![fb crowdfunding banner-pt2](https://cloud.githubusercontent.com/assets/7097315/10327795/5fe5046a-6c71-11e5-8920-4a8c74b29b1e.jpg)

Could we use 2 smaller images, that would run on the same line. So that for screens larger than the 350px, it would appear as one (more or less), like this:
![fb crowdfunding banner-total](https://cloud.githubusercontent.com/assets/7097315/10327821/c2561396-6c71-11e5-8d8f-a702166c22dc.jpg)

but be broken up into the two parts for smaller screens.

**Comment by radioprotector** [comment]
I like that idea. It might be easier to compress as well.

**Comment by internetcreep** [comment]
Cool. Let me tweak with the image a little. The two logos look like nipples to me now

**Comment by internetcreep** [comment]
Input kind of filtered out last night, but I think we'll just go with 
Dropbox/RAD Business/Grants & Fundraising/Crowdfunding/website crowdfunding banner-pt1.jpg
Dropbox/RAD Business/Grants & Fundraising/Crowdfunding/website crowdfunding banner-pt2.jpg

**Comment by internetcreep** [comment]
I also just realized that there should be a link added to the /donate/ page too
