### ISSUE TITLE
Update privacy policy

### ISSUE THREAD

**Issue by radioprotector** [radremedy/radremedy#328]
The language needs to be a little clearer as to what we track and why.

**Comment by internetcreep** [comment]
Is the search history data we have access to tied to users/IPs or is that just aggregates?

Should we mention 3rd party sites? Like paypal, mailchimp, etc. 

And maybe we should also specifically say that we won't sell or give away their info. Or is that more TOS?

**Comment by radioprotector** [comment]
Search history is tracked on the server log level, so I could update it to mention that we track usage in that way but keep that data in-house and don't share it with third parties.

We could add something like "The data we share with third-party sites such as PayPal and MailChimp is only to the extent needed for processing transactions and sending emails."
