### ISSUE TITLE
Investigate paging behavior for resources

### ISSUE THREAD

**Issue by radioprotector** [radremedy/radremedy#343]
We may be invalidly getting 404s when there is a second page of data, like in:
[http://radremedy.org/find-provider/?search=&addr=&dist=-1&lat=&long=&categories=94&categories=122&categories=95&categories=96&order_by=rating#results](http://radremedy.org/find-provider/?search=&addr=&dist=-1&lat=&long=&categories=94&categories=122&categories=95&categories=96&order_by=rating#results)

**Comment by approximatelylinear** [comment]
Hi! I've been meaning to contribute for a bit. It looks like in this case, the set of categories in the url is getting truncated in the page 2 uri.

Original: `http://radremedy.org/find-provider/?search=&addr=&dist=-1&lat=&long=&categories=94&categories=122&categories=95&categories=96&order_by=rating#results`

Page 2: `http://radremedy.org/find-provider/page/2?search=&dist=-1&addr=&long=&lat=&order_by=rating&categories=94#results`


Modifying the original full uri to specify the second page seems to have the right effect, so the culprit may be the truncation: 

Manually constructed page 2 uri: `http://radremedy.org/find-provider/page/2?search=&addr=&dist=-1&lat=&long=&categories=94&categories=122&categories=95&categories=96&order_by=rating#results`

**Comment by radioprotector** [comment]
Thanks for taking a look at this!

It looks like that would be caused by a broken implementation of the URL generation, which in this case is [the remedyblueprint.py's url_for_other_page function](https://github.com/radremedy/radremedy/blob/master/remedy/remedyblueprint.py#L78).

It looks like this may have been introduced by [PR 207](https://github.com/radremedy/radremedy/commit/07fd345851d252eb520df72df2ca1a61d79d4765) because the recommended pagination snippet was failing to handle query string arguments.

However, I suspect that the `request.args.to_dict().items()` call is the culprit. According to the [Werkzeug documentation](http://werkzeug.pocoo.org/docs/0.11/datastructures/#werkzeug.datastructures.MultiDict), `to_dict()` will discard multiple values if the `flat` argument is True (the default).

I think the internals of this need to be reworked to:

1. Create a `MultiDict` based on `request.view_args`.
2. Update that multidict based on `request.args`.
3. Set `page` and `_anchor` as appropriate.
4. Pass that to `url_for`.

I *think* (but have not verified) that `url_for` [will gracefully handle list-type argument values](https://github.com/pallets/werkzeug/issues/658#issuecomment-72022911).
